services:
  - type: web
    name: django-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn expensetrack.wsgi:application --bind 0.0.0.0:$PORT
    autoDeploy: true
